import {Sparkles,Clock3,ArrowUpRight} from 'lucide-react';
type Article={model_name?:string;summary:string;ai_generated:boolean;key_points?:string[];ai_status?:string;ai_attempts?:number};
export type SummaryStatus={ai_configured:boolean;ai_daily_limit:number;ai_attempts_today:number;ai_resets_at?:string;provider?:{reason:string;retry_at:string;blocked:boolean}|null};
export function NewsSummary({article,status,vi,sourceUrl}:{article:Article;status:SummaryStatus|null;vi:boolean;sourceUrl:string}){
 const full=!!status&&status.ai_attempts_today>=status.ai_daily_limit;
 const exhausted=(article.ai_attempts||0)>=3;
 const provider=status?.provider?.blocked?status.provider:null;
 const when=(value?:string)=>value?new Date(value).toLocaleString(vi?'vi-VN':'en-GB',{timeZone:'Asia/Bangkok',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' (UTC+7)':(vi?'00:00 ngày tiếp theo (UTC+7)':'00:00 next day (UTC+7)');
 const label=provider?.reason==='insufficient_balance'?(vi?'Không đủ số dư API':'Insufficient API balance'):full?(vi?'Đã hết lượt hôm nay':'Daily limit reached'):provider?(vi?'Dịch vụ AI tạm dừng':'AI service paused'):exhausted?(vi?'Chưa tạo được tóm tắt':'Summary unavailable'):article.ai_status==='processing'?(vi?'Đang xử lý':'Processing'):(vi?'Đang chờ':'Queued');
 const message=!status?(vi?'Đang kiểm tra trạng thái tóm tắt.':'Checking summary status.'):!status.ai_configured?(vi?'Dịch vụ AI chưa được cấu hình.':'AI is not configured.'):full?(vi?`Đã dùng ${status.ai_attempts_today}/${status.ai_daily_limit} lượt. Hạn mức ứng dụng đặt lại lúc ${when(status.ai_resets_at)}. Khi đó hệ thống mới có thể thử tiếp nếu dịch vụ AI sẵn sàng.`:`Used ${status.ai_attempts_today}/${status.ai_daily_limit} attempts. The app budget resets at ${when(status.ai_resets_at)}; retries also depend on provider availability.`):provider?(provider.reason==='insufficient_balance'?(vi?'Z.ai báo không đủ số dư hoặc chưa có gói tài nguyên API (mã 1113). Cần kiểm tra Billing của tài khoản API; chờ đến giờ thử lại không khắc phục được lỗi này. Tìm kiếm và lưu nguồn vẫn dùng được.':'Z.ai reports insufficient API balance or no resource package (1113). Check API billing; waiting will not resolve this. Search and saved sources remain available.'):provider.reason==='authorization'?(vi?'Khóa AI bị nhà cung cấp từ chối. Cần kiểm tra cấu hình dịch vụ.':'The provider rejected the AI credentials. Service configuration needs checking.'):(vi?`Nhà cung cấp tạm giới hạn yêu cầu. Hệ thống chờ đến ${when(provider.retry_at)} trước khi thử tiếp.`:`The provider is temporarily unavailable. Retries resume after ${when(provider.retry_at)}.`)):exhausted?(vi?'Đã thử 3 lần nhưng chưa thành công. Bạn có thể đọc thông tin từ nguồn bên dưới.':'Three attempts failed. You can read the source preview below.'):(vi?'Bài đang trong hàng đợi. Khi xử lý thành công, tóm tắt sẽ tự xuất hiện.':'This article is queued. Its summary appears automatically when processing succeeds.');
 if(article.ai_generated)return <section className="nr-ai-box"><div className="nr-ai-title"><Sparkles size={21}/><h2>{vi?'Tóm tắt AI':'AI summary'}</h2><span>{article.model_name||'AI'}</span></div><p className="nr-summary">{article.summary}</p>{!!article.key_points?.length&&<><h3>{vi?'Những ý chính':'Key takeaways'}</h3><ul>{article.key_points.map((point,i)=><li key={i}>{point}</li>)}</ul></>}<small>{vi?'Dựa trên thông tin nguồn cung cấp, có thể chỉ là tiêu đề hoặc trích đoạn; không phải toàn văn.':'Based on supplied source information, which may be only a headline or excerpt, not the full article.'}</small></section>;
 return <section className="nr-summary-preview"><div className="nr-summary-state" role="status"><Clock3 size={17}/><div><strong>{label}</strong><p>{message}</p></div></div><h2>{vi?'Thông tin từ nguồn':'Source preview'}</h2><p className="nr-preview-text">{article.summary}</p><small>{vi?'Đây là nội dung nguồn cung cấp, chưa phải bản tóm tắt hay bản dịch AI.':'This is the supplied source preview, not an AI summary or translation.'}</small><a href={sourceUrl} target="_blank" rel="noopener noreferrer">{vi?'Đọc tại nguồn':'Read at source'}<ArrowUpRight size={16}/></a></section>
}
