'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useLocale} from '@/components/ui/Language';
type Entry={id:string;title:string;source_name:string;source_url:string;opened_at:string};
const key='vesper-news-history';
export function recordNewsVisit(article:Omit<Entry,'opened_at'>){try{const raw=JSON.parse(localStorage.getItem(key)||'[]');const old:Entry[]=Array.isArray(raw)?raw:[];localStorage.setItem(key,JSON.stringify([{id:article.id,title:article.title,source_name:article.source_name,source_url:article.source_url,opened_at:new Date().toISOString()},...old.filter(x=>x.id!==article.id)].slice(0,200)));window.dispatchEvent(new Event('news-history-change'))}catch{}}
export default function NewsHistory(){const vi=useLocale()==='vi';const [entries,setEntries]=useState<Entry[]>([]);const [error,setError]=useState('');
useEffect(()=>{const read=()=>{try{const raw=JSON.parse(localStorage.getItem(key)||'[]');setEntries(Array.isArray(raw)?raw.filter(x=>typeof x.id==='string'&&typeof x.title==='string'):[])}catch{setEntries([])}};read();window.addEventListener('storage',read);window.addEventListener('news-history-change',read);return()=>{window.removeEventListener('storage',read);window.removeEventListener('news-history-change',read)}},[]);
function remove(id?:string){try{const raw=JSON.parse(localStorage.getItem(key)||'[]');const next=id?(Array.isArray(raw)?raw:[]).filter((x:Entry)=>x.id!==id):[];localStorage.setItem(key,JSON.stringify(next));setEntries(next);window.dispatchEvent(new Event('news-history-change'))}catch{setError(vi?'Không xóa được lịch sử.':'Could not remove history.')}}
function download(){try{const data:Record<string,unknown>={version:1,exported_at:new Date().toISOString()};for(const [name,k] of Object.entries({history:key,saved_articles:'vesper-news-saved',research_notes:'vesper-research-notes',search:'vesper-news-search'})){try{data[name]=JSON.parse(localStorage.getItem(k)||'null')}catch{data[name]=null}}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='vespersignal-news-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError(vi?'Không xuất được dữ liệu.':'Could not export data.')}}
return <section className="nr-project-intro"><nav><button onClick={download}>{vi?'Tải dữ liệu News (.json)':'Download News data (.json)'}</button><Link href="/research-notes">{vi?'Bài và ghi chú đã lưu':'Saved articles and notes'}</Link></nav><details><summary style={{cursor:'pointer',marginTop:16}}>{vi?'Lịch sử vừa xem':'Recently viewed'} ({entries.length})</summary><p>{vi?'Lưu trên trình duyệt này, tối đa 200 bài gần nhất. File tải xuống gồm lịch sử, bài đã lưu, ghi chú và chủ đề tìm kiếm.':'Stored in this browser, up to 200 recent articles. Export includes history, saved articles, notes and your search topic.'}</p>{entries.length>0&&<button onClick={()=>remove()}>{vi?'Xóa toàn bộ lịch sử':'Clear viewing history'}</button>}{entries.length?<ol>{entries.map(x=><li key={x.id} style={{padding:'10px 0'}}><Link href={'/news/'+encodeURIComponent(x.id)}>{x.title}</Link><small style={{display:'block',color:'var(--nr-muted)'}}>{x.source_name} · {new Date(x.opened_at).toLocaleString(vi?'vi-VN':'en-GB')}</small><button onClick={()=>remove(x.id)} aria-label={(vi?'Xóa khỏi lịch sử: ':'Remove from history: ')+x.title}>{vi?'Xóa':'Remove'}</button></li>)}</ol>:<p>{vi?'Chưa mở bài viết nào.':'No articles viewed yet.'}</p>}</details>{error&&<p role="alert">{error}</p>}</section>}
