"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Newspaper,Search,Sparkles,ArrowUpRight,ArrowLeft,Bookmark,Check,RefreshCw,ChartNoAxesCombined,Cpu,Clock,Link2,Download,ArrowRight,Layers,BookOpen,Wrench} from 'lucide-react';
import {LanguageSwitch,useLocale} from '@/components/ui/Language';
import {ThemeToggle} from '@/components/ui/ThemeToggle';
import './news.css';
import './news-categories.css';
import {NewsSummary} from './NewsSummary';
import NewsHistory,{recordNewsVisit} from './NewsHistory';
import NewsFeedback from './NewsFeedback';
import WebDiscovery from './WebDiscovery';
import './research-discovery.css';
type Article={id:string;title:string;summary:string;source_name:string;source_url:string;published_at:string;category:string;ai_generated:boolean;language:string;key_points?:string[];ai_status?:string;generated_at?:string};
type Status={sources?:{id:string;name:string;category:string;url:string}[];pipeline:{last_refresh:string;last_success:string;last_result:{failed_sources?:number}}|null;categories:{category:string;count:number}[];ai_ready:number;ai_configured:boolean;ai_daily_limit:number;ai_attempts_today:number};
export default function NewsView({id}:{id?:string}){
 const vi=useLocale()==='vi';const language=vi?'vi':'en';
 const [category,setCategory]=useState('');const [period,setPeriod]=useState('all');const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [total,setTotal]=useState(0);
 const [items,setItems]=useState<Article[]>([]);const [article,setArticle]=useState<Article|null>(null);const [related,setRelated]=useState<Article[]>([]);const [status,setStatus]=useState<Status|null>(null);
 useEffect(()=>{if(article&&id)recordNewsVisit(article)},[id,article?.id]); // eslint-disable-line react-hooks/exhaustive-deps
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [tick,setTick]=useState(0);const [saved,setSaved]=useState<Article[]>([]);const [savedOnly,setSavedOnly]=useState(false);const [ready,setReady]=useState(false);const [read,setRead]=useState<string[]>([]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('vesper-news-saved')||'[]');if(Array.isArray(s))setSaved(s.filter(x=>typeof x.id==='string'&&typeof x.title==='string').slice(0,100));const r=JSON.parse(localStorage.getItem('vesper-news-read')||'[]');if(Array.isArray(r))setRead(r.filter(x=>typeof x==='string').slice(0,500))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('vesper-news-saved',JSON.stringify(saved));localStorage.setItem('vesper-news-read',JSON.stringify(read))}catch{setNotice(vi?'Không đủ bộ nhớ để lưu bài.':'Unable to save in this browser.')}},[saved,read,ready,vi]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setTick(t=>t+1)},id?15000:60000);return()=>clearInterval(timer)},[id]);
 useEffect(()=>{const ctrl=new AbortController();setError('');setLoading(true);const qs=new URLSearchParams({language,limit:'12',offset:String(offset),period});if(category)qs.set('category',category);if(query)qs.set('q',query);
  fetch(id?`/api/news/${id}?language=${language}`:`/api/news?${qs}`,{signal:ctrl.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error(r.status===404?(vi?'Chưa có bài ở ngôn ngữ này. Hãy thử VI hoặc chờ bản dịch AI.':'No article in this language yet. Try Vietnamese or wait for AI translation.'):(vi?'Chưa tải được tin. Hãy thử lại.':'Could not load news. Please retry.'));return r.json()}).then(d=>{if(id)setArticle(d);else{setItems(d.items);setTotal(d.total)}}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)});
  fetch('/api/news/status',{signal:ctrl.signal,cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(d)setStatus(d)}).catch(()=>{});return()=>ctrl.abort();
 },[id,language,category,period,query,offset,tick,vi]);
 useEffect(()=>{if(!article||!id)return;const ctrl=new AbortController();fetch(`/api/news?language=${language}&category=${article.category}&limit=5`,{signal:ctrl.signal}).then(r=>r.ok?r.json():null).then(d=>{if(d)setRelated(d.items.filter((x:Article)=>x.id!==id).slice(0,3))}).catch(()=>{});return()=>ctrl.abort()},[id,language,article?.category]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{
  if(!savedOnly)return;
  const ctrl=new AbortController();
  const stale=saved.filter(a=>a.language!==language);
  Promise.all(stale.map(a=>fetch(`/api/news/${a.id}?language=${language}`,{signal:ctrl.signal}).then(r=>r.ok?r.json():null).catch(()=>null))).then(rows=>{
   if(ctrl.signal.aborted)return;
   const replacements=new Map(rows.filter(Boolean).map(a=>[a.id,a]));
   setSaved(old=>old.map(a=>replacements.get(a.id)||a));
  });
  return()=>ctrl.abort();
 },[savedOnly,language]); // eslint-disable-line react-hooks/exhaustive-deps
 const localized=(a:Article)=>a.language===language?a:{...a,title:vi?'Bài viết đang chờ bản dịch tiếng Việt':'Article awaiting English translation',summary:vi?'Bản dịch chưa sẵn sàng. Mở nguồn để đọc bản gốc.':'Translation unavailable. Open the source to read the original.',ai_generated:false,key_points:[]};
 const date=(value:string)=>!value?(vi?'Nguồn không ghi ngày':'Date not provided'):new Date(value).toLocaleString(vi?'vi-VN':'en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
 const cat=(c:string)=>({economy:vi?'Kinh tế':'Economy',technology:vi?'Công nghệ':'Technology',research:vi?'Nghiên cứu':'Research',web:vi?'Khám phá web':'Web discovery',ai:vi?'Trí tuệ nhân tạo':'Artificial intelligence',tools:vi?'Công cụ':'Tools'}[c]||c);
 const href=(a:Article)=>{try{const u=new URL(a.source_url);return u.protocol==='https:'?u.href:'#'}catch{return '#'}};
 const toggle=(a:Article)=>setSaved(prev=>prev.some(x=>x.id===a.id)?prev.filter(x=>x.id!==a.id):[a,...prev].slice(0,100));
 const mark=(a:Article)=>setRead(prev=>Array.from(new Set([a.id,...prev])).slice(0,500));
 const shown=savedOnly?saved.filter(a=>(!category||a.category===category)&&a.title.toLowerCase().includes(query.toLowerCase())):items;
 const title=vi?'Mọi chuyển động,':'Every development,';const subtitle=vi?'gom về một chỗ.':'all in one place.';
 const filter=(c:string)=>{setCategory(c);setOffset(0)};
 function summaryDownload(a:Article){const text=`${a.title}\n${date(a.published_at)} · ${a.source_name}\n\n${a.summary}\n\n${(a.key_points||[]).map(s=>'• '+s).join('\n')}\n\n${a.source_url}\n\n${vi?'Tóm tắt AI dựa trên trích đoạn RSS, không phải toàn văn.':'AI summary based on RSS excerpt, not the full article.'}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const el=document.createElement('a');el.href=url;el.download=`vespersignal-news-${a.id}.txt`;el.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const card=(raw:Article,featured=false)=>{const a=localized(raw);return <article className={`nr-card ${featured?'nr-featured':''}`} key={a.id}><div className={`nr-card-icon ${a.category}`}>{a.category==='economy'?<ChartNoAxesCombined size={featured?32:23}/>:<Cpu size={featured?32:23}/>}</div><div className="nr-card-body"><div className="nr-meta"><span>{cat(a.category)}</span><span>{a.source_name}</span>{a.ai_generated&&<b><Sparkles size={11}/>AI</b>}{read.includes(a.id)&&<Check size={12}/>}</div><Link href={'/news/'+a.id} onClick={()=>mark(a)}><h3>{a.title}</h3></Link><p>{a.summary}</p><div className="nr-card-bottom"><time><Clock size={12}/>{date(a.published_at)}</time><div><a href={href(a)} target="_blank" rel="noopener noreferrer" title={vi?'Nguồn gốc':'Original source'}><ArrowUpRight size={17}/></a><button title={vi?'Lưu bài':'Save article'} aria-pressed={saved.some(x=>x.id===a.id)} onClick={()=>toggle(a)}><Bookmark size={16} fill={saved.some(x=>x.id===a.id)?'currentColor':'none'}/></button></div></div></div></article>};
 return <main className="newsroom"><header className="nr-header"><Link href="/news" className="nr-logo"><Newspaper size={21}/><strong>VesperSignal<span> News</span></strong></Link><nav><Link href="/news">{vi?'Bảng tin':'Feed'}</Link></nav><div className="nr-header-right"><ThemeToggle/><LanguageSwitch compact/></div></header>
 {!id&&<><section className="nr-hero"><span className="nr-kicker">{vi?'BẢN TIN KINH TẾ & CÔNG NGHỆ':'ECONOMY & TECHNOLOGY BRIEFING'}</span><h1>{title}<br/><em>{subtitle}</em></h1><p>{vi?'Tin mới từ nguồn gốc, tóm tắt ngắn gọn bằng AI. Đọc nhanh, hiểu ý chính và luôn biết thông tin đến từ đâu.':'Fresh news from original sources, summarized by AI. Read quickly, understand the key facts, and always know the source.'}</p></section><div className="nr-promises">{[[Layers,vi?'Kinh tế & công nghệ':'Economy & technology'],[Sparkles,vi?'Tóm tắt bằng AI':'AI summaries'],[Link2,vi?'Luôn dẫn nguồn':'Always linked to sources'],[RefreshCw,vi?'Tự cập nhật 15 phút':'Updates every 15 minutes']].map(([Icon,label],i)=>{const I=Icon as typeof Layers;return <div key={i}><I size={19}/><span>{label as string}</span></div>})}</div></>}
 <div className="nr-container">
 {!id&&<><section className="nr-project-intro"><span>{vi?'Ý TƯỞNG DỰ ÁN · BẢN DEMO':'PROJECT VISION · DEMO'}</span><h2>{vi?'Ít tab hơn. Nhiều thời gian để hiểu hơn.':'Fewer tabs. More time to understand.'}</h2><p>{vi?'Dành cho sinh viên và người làm nghiên cứu: tìm kiếm, đọc và quản lý nguồn tài liệu trong cùng một nơi. Tìm theo chủ đề, chọn nguồn hữu ích và để AI tổng hợp nội dung kèm trích dẫn. Bảng tin bên dưới tiếp tục cập nhật theo thời gian.':'For students and researchers: find, read and manage sources in one place. Search a topic, choose useful evidence and generate an AI synthesis with citations. The news feed below keeps updating over time.'}</p><nav><Link href="/about">{vi?'Đọc ý tưởng dự án':'About the project'} →</Link><Link href="/research-notes">{vi?'Bài và ghi chú đã lưu':'Saved articles and notes'} →</Link></nav></section><div id="research-search"><WebDiscovery/></div><NewsHistory/></>}
 {notice&&<p role="status" className="nr-notice">{notice}<button onClick={()=>setNotice('')}>×</button></p>}
 {id?<><Link href="/news" className="nr-back"><ArrowLeft size={16}/>{vi?'Về bảng tin':'Back to feed'}</Link>{loading?<div className="nr-state" role="status">{vi?'Đang tải bài viết…':'Loading article…'}</div>:error?<div className="nr-state" role="alert">{error}<button onClick={()=>setTick(t=>t+1)}>{vi?'Thử lại':'Retry'}</button></div>:article&&<div className="nr-detail-layout"><article className="nr-detail"><div className="nr-meta"><span>{cat(article.category)}</span><span>{article.source_name}</span><time>{date(article.published_at)}</time></div><h1>{localized(article).title}</h1>{!article.ai_generated&&<p className="nr-notice">{vi?'Nội dung gốc từ nguồn. Bản dịch và tóm tắt tiếng Việt sẽ hiển thị khi AI xử lý xong.':'Original source content. The English translation and summary will appear after AI processing.'}</p>}<div className="nr-detail-actions"><button onClick={()=>toggle(article)}><Bookmark size={16}/>{saved.some(a=>a.id===article.id)?(vi?'Đã lưu':'Saved'):(vi?'Lưu bài':'Save')}</button><button onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setNotice(vi?'Đã sao chép liên kết.':'Link copied.')}catch{setNotice(vi?'Không sao chép được liên kết.':'Could not copy link.')}}}><Link2 size={16}/>{vi?'Chia sẻ':'Share'}</button>{article.ai_generated&&<button onClick={()=>summaryDownload(article)}><Download size={16}/>{vi?'Tải tóm tắt':'Download summary'}</button>}</div>
 <NewsSummary article={localized(article)} status={status} vi={vi} sourceUrl={href(article)}/>
 <div className="nr-source-box"><div><span>{vi?'ĐỌC ĐẦY ĐỦ TẠI NGUỒN':'READ THE ORIGINAL'}</span><h3>{article.source_name}</h3><p>{vi?'Kiểm tra bối cảnh và toàn bộ nội dung tại nơi xuất bản.':'Read the complete context at the publisher.'}</p></div><a href={href(article)} target="_blank" rel="noopener noreferrer">{vi?'Mở bài gốc':'Read original'}<ArrowUpRight size={18}/></a></div><button className="nr-read" onClick={()=>{mark(article);setNotice(vi?'Đã đánh dấu đọc xong.':'Marked as read.')}}><Check size={16}/>{vi?'Đánh dấu đã đọc':'Mark as read'}</button></article><aside className="nr-aside"><div className="nr-panel"><h3>{vi?'Cùng chuyên mục':'Related reading'}</h3>{related.map(a=><Link className="nr-related" href={'/news/'+a.id} key={a.id}>{a.title}<ArrowUpRight size={14}/></Link>)}</div></aside></div>}</>:<>
 {!query&&!category&&!savedOnly&&offset===0&&!!items.length&&<section className="nr-feature-section"><div className="nr-section-title"><div><span>{vi?'ĐÁNG CHÚ Ý':'WORTH READING'}</span><h2>{vi?'Bắt đầu từ những tin mới':'Start with the latest'}</h2></div><span className="nr-read-count"><Check size={14}/>{read.length} {vi?'bài đã đọc':'read'}</span></div><div className="nr-feature-grid">{items.slice(0,3).map(a=>card(a,true))}</div></section>}
 <div className="nr-layout"><section id="feed"><div className="nr-section-title"><h2>{savedOnly?(vi?'Bài đã lưu':'Saved articles'):(vi?'Bảng tin':'News feed')}</h2><span>{savedOnly?saved.length:total} {vi?'bài viết':'articles'}</span></div><form className="nr-search" onSubmit={e=>{e.preventDefault();setQuery(search.trim());setOffset(0)}}><Search size={17}/><input value={search} maxLength={200} onChange={e=>setSearch(e.target.value)} placeholder={vi?'Tìm bài viết, chủ đề…':'Search articles, topics…'} aria-label={vi?'Tìm bài viết':'Search articles'}/><button>{vi?'Tìm':'Search'}</button></form><div className="nr-tabs"><button className={!savedOnly&&period==='all'?'active':''} onClick={()=>{setSavedOnly(false);setPeriod('all');setOffset(0)}}>{vi?'Mới nhất':'Latest'}</button><button className={!savedOnly&&period==='week'?'active':''} onClick={()=>{setSavedOnly(false);setPeriod('week');setOffset(0)}}>{vi?'Tuần này':'This week'}</button><button className={savedOnly?'active':''} onClick={()=>setSavedOnly(true)}><Bookmark size={13}/>{vi?'Đã lưu':'Saved'}</button></div><div className="nr-categories">{['','economy','technology','research','ai','tools'].map(c=><button className={category===c?'active':''} aria-pressed={category===c} key={c} onClick={()=>filter(c)}>{c?cat(c):(vi?'Tất cả':'All')}</button>)}</div>
 {loading?<div className="nr-state" role="status">{vi?'Đang tải bảng tin…':'Loading feed…'}</div>:error?<div role="alert" className="nr-state">{error}<button onClick={()=>setTick(t=>t+1)}>{vi?'Thử lại':'Retry'}</button></div>:shown.length?<div className="nr-feed">{shown.map(a=>card(a))}</div>:<div className="nr-state">{savedOnly?(vi?'Bạn chưa lưu bài phù hợp. Bấm biểu tượng đánh dấu trên bài để lưu.':'No matching saved articles. Bookmark an article to save it.'):(vi?'Chưa có bài phù hợp. Thử bỏ bộ lọc hoặc chuyển sang VI.':'No matching articles. Try another filter or switch to Vietnamese.')}</div>}
 {!savedOnly&&<div className="nr-pagination"><button disabled={offset===0} onClick={()=>setOffset(v=>Math.max(0,v-12))}>← {vi?'Trước':'Previous'}</button><span>{Math.floor(offset/12)+1} / {Math.max(1,Math.ceil(total/12))}</span><button disabled={offset+12>=total} onClick={()=>setOffset(v=>v+12)}>{vi?'Tiếp':'Next'} →</button></div>}</section><aside className="nr-aside"><div className="nr-panel"><h3>{vi?'Danh mục':'Categories'}</h3>{['economy','technology','research','ai','tools'].map(c=><button className="nr-category-row" aria-pressed={category===c} key={c} onClick={()=>filter(c)}><span>{c==='economy'?<ChartNoAxesCombined size={16}/>:c==='research'?<BookOpen size={16}/>:c==='ai'?<Sparkles size={16}/>:c==='tools'?<Wrench size={16}/>:<Cpu size={16}/>} {cat(c)}</span><b>{status?.categories.find(x=>x.category===c)?.count??'—'}</b></button>)}</div><div className="nr-panel"><h3><span className="nr-dot"/>{vi?'Nhịp cập nhật':'Update status'}</h3><p>{vi?'Lấy tin mới mỗi 15 phút. Bảng tin tự làm mới mỗi phút.':'New RSS items every 15 minutes. The feed refreshes every minute.'}</p><dl><dt>{vi?'Đã kiểm tra nguồn':'Sources checked'}</dt><dd>{status?.pipeline?.last_refresh?date(status.pipeline.last_refresh):'—'}</dd><dt>{vi?'Tóm tắt AI sẵn sàng':'AI summaries ready'}</dt><dd>{status?.ai_ready??'—'}</dd></dl>{!!status?.pipeline?.last_result?.failed_sources&&<p className="nr-warning">{vi?'Một nguồn đang lỗi. Tin đã lưu vẫn đọc được.':'A source is unavailable. Stored articles remain available.'}</p>}</div><div className="nr-panel"><h3>{vi?'Nguồn tin':'Sources'}</h3>{status?.sources?.length?<div style={{display:'grid',gap:12,marginBottom:16}}>{Array.from(new Map(status.sources.map(source=>[source.name,source])).values()).map(source=><a key={source.id} href={source.url} target="_blank" rel="noopener noreferrer" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,fontSize:12}}><span>{source.name}<small style={{display:'block',color:'var(--nr-muted)',fontSize:10}}>{source.id.startsWith('arxiv')?(vi?'Nghiên cứu sơ bộ':'Preprints'):source.id.startsWith('medium')?(vi?'Bài viết cộng đồng':'Community posts'):source.category==='financial_crime'?(vi?'Cơ quan quản lý':'Regulatory reports'):cat(source.category)}</small></span><ArrowUpRight size={14}/></a>)}</div>:<p>{vi?'Chưa tải được danh sách nguồn.':'Source list is not available yet.'}</p>}<p>{vi?'Danh sách nguồn RSS đã cấu hình; từng nguồn có thể tạm gián đoạn. Mở liên kết để đối chiếu. Nhiều nguồn không đồng nghĩa thông tin đã được xác minh. Bản quyền thuộc nơi xuất bản.':'Configured RSS feeds; individual sources may be temporarily unavailable. Open links to compare reporting. Multiple sources do not mean verified claims. Copyright remains with publishers.'}</p></div></aside></div></>}
 </div><footer className="nr-footer"><div><Link className="nr-logo" href="/news"><Newspaper size={22}/><strong>VesperSignal News</strong></Link><p>{vi?'Đọc nhanh, hiểu ý chính, luôn dẫn nguồn.':'Read quickly, understand the facts, always linked to sources.'}</p></div><nav><Link href="/news">{vi?'Bảng tin':'Feed'}</Link><NewsFeedback/></nav><small>{vi?'Bản local: cập nhật tự động khi máy và backend đang chạy. Tóm tắt AI dựa trên trích đoạn RSS.':'Local edition: automatic updates while the computer and backend are running. AI summaries use RSS excerpts.'}</small></footer></main>
}



