'use client';
import {useEffect,useRef,useState} from 'react';
import {useLocale} from '@/components/ui/Language';
export default function NewsFeedback(){const vi=useLocale()==='vi';const dialog=useRef<HTMLDialogElement>(null);const [invite,setInvite]=useState(false);const [rating,setRating]=useState(0);const [comment,setComment]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const requestId=useRef('');
useEffect(()=>{const started=Date.now();const timer=setInterval(()=>{try{if(localStorage.getItem('news-feedback-sent')||sessionStorage.getItem('news-feedback-dismissed'))return;const history=JSON.parse(localStorage.getItem('vesper-news-history')||'[]');if(document.visibilityState==='visible'&&Date.now()-started>=60000&&Array.isArray(history)&&history.length){setInvite(true);clearInterval(timer)}}catch{}},10000);return()=>clearInterval(timer)},[]);
function dismiss(){setInvite(false);try{sessionStorage.setItem('news-feedback-dismissed','1')}catch{}}
async function send(){setBusy(true);setMessage('');if(!rating){setMessage(vi?'Vui lòng chọn số sao.':'Please select a rating.');setBusy(false);return}if(!requestId.current)requestId.current=crypto.randomUUID();try{const r=await fetch('/api/news/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,rating,comment,language:vi?'vi':'en'})});const data=await r.json().catch(()=>null);if(!r.ok)throw Error(data?.detail||(vi?'Chưa gửi được đánh giá.':'Could not submit feedback.'));try{localStorage.setItem('news-feedback-sent','1')}catch{}setMessage(vi?'Cảm ơn bạn! Đánh giá đã được lưu.':'Thank you! Your feedback has been saved.');setInvite(false)}catch(error){setMessage(error instanceof Error?error.message:(vi?'Chưa gửi được. Nội dung vẫn được giữ, bạn hãy thử lại.':'Could not send. Your feedback is preserved; please retry.'))}finally{setBusy(false)}}
return <><div style={{margin:0,fontSize:12,color:'var(--nr-muted)'}}><button onClick={()=>dialog.current?.showModal()}>{vi?'Góp ý trải nghiệm News':'Give feedback on News'}</button></div>{invite&&<aside role="status" style={{padding:16,border:'1px solid var(--nr-border)',borderRadius:12,marginBottom:20}}><p>{vi?'Bạn thấy trải nghiệm tìm và đọc tin thế nào? Đánh giá của bạn giúp cải thiện bản demo.':'How was your experience finding and reading news? Your feedback helps improve the demo.'}</p><button onClick={()=>dialog.current?.showModal()}>{vi?'Đánh giá':'Rate experience'}</button> · <button onClick={dismiss}>{vi?'Để sau':'Later'}</button></aside>}
<dialog ref={dialog} style={{width:'min(460px,90vw)',padding:24,borderRadius:16,border:'1px solid var(--nr-border)',background:'var(--nr-surface)',color:'var(--nr-text)'}}><button style={{float:'right'}} aria-label={vi?'Đóng':'Close'} onClick={()=>{dialog.current?.close();dismiss()}}>×</button><h2>{vi?'Đánh giá VesperSignal News':'Rate VesperSignal News'}</h2><p style={{fontSize:12,margin:'12px 0'}}>{vi?'Tự nguyện, không cần đăng nhập. Chỉ gửi số sao, góp ý và ngôn ngữ; không gửi lịch sử đọc. Tránh nhập thông tin cá nhân.':'Optional, no login required. Only rating, comment and language are sent, not reading history. Please avoid personal information.'}</p><div role="group" aria-label={vi?'Số sao':'Rating'}>{[1,2,3,4,5].map(n=><button key={n} aria-pressed={rating===n} aria-label={`${n}/5`} onClick={()=>setRating(n)} style={{fontSize:28,color:n<=rating?'#a3e635':'#888',padding:6}}>★</button>)}</div><label>{vi?'Góp ý (không bắt buộc)':'Comment (optional)'}<textarea value={comment} maxLength={2000} onChange={e=>setComment(e.target.value)} rows={4} style={{display:'block',width:'100%',margin:'12px 0',padding:10,background:'var(--nr-bg)',color:'inherit',border:'1px solid var(--nr-border)'}}/></label><button disabled={!rating||busy||message.includes('đã được lưu')||message.includes('has been saved')} onClick={send}>{busy?(vi?'Đang gửi…':'Sending…'):(vi?'Gửi đánh giá':'Submit feedback')}</button><p role="status">{message}</p></dialog></>}
