'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Sparkles,Download,Bookmark,Check,ArrowUpRight,Loader2} from 'lucide-react';
import {useLocale} from '@/components/ui/Language';
import './research.css';
type Source={id:string;title:string;source_name:string;source_url:string;published_at:string|null;authors?:string[]};
type Evidence={number:number;id:string;title:string;url:string;publisher:string;authors:string[];year:number|null;coverage:string};
type Answer={status:string;detail?:string;sources:Evidence[];paragraphs?:{text:string;sources:number[]}[];limitations?:string};
export default function ResearchSummary({query,items}:{query:string;items:Source[]}){
 const vi=useLocale()==='vi';const [selected,setSelected]=useState<string[]>([]);const [answer,setAnswer]=useState<Answer|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [login,setLogin]=useState(false);const [saved,setSaved]=useState(false);const request=useRef<AbortController|null>(null);
 const signature=items.map(x=>x.id).join(',');
 useEffect(()=>{request.current?.abort();setSelected(items.slice(0,6).map(x=>x.id));setAnswer(null);setError('');setBusy(false);setSaved(false);return()=>request.current?.abort();},[query,signature,vi]); // eslint-disable-line react-hooks/exhaustive-deps
 const sources:Evidence[]=answer?.sources||items.filter(x=>selected.includes(x.id)).map((x,i)=>({number:i+1,id:x.id,title:x.title,url:x.source_url,publisher:x.source_name,authors:x.authors||[],year:x.published_at?new Date(x.published_at).getFullYear():null,coverage:'not_analyzed'}));
 async function summarize(){const ctrl=new AbortController();request.current=ctrl;setBusy(true);setError('');setLogin(false);setSaved(false);
  try{const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,language:vi?'vi':'en',source_ids:selected}),signal:ctrl.signal});const data=await r.json();if(!r.ok){setLogin(r.status===401);throw Error(data.detail||'Unavailable')}setAnswer(data)}catch(e){if(!ctrl.signal.aborted)setError(e instanceof Error?e.message:'Unavailable')}finally{if(!ctrl.signal.aborted)setBusy(false)}
 }
 function text(){return `# ${query}\n\n${answer?.paragraphs?.map(p=>p.text+' '+p.sources.map(n=>`[${n}]`).join(' ')).join('\n\n')||''}\n\n${answer?.limitations||''}\n\n## ${vi?'Nguồn tham khảo':'Sources'}\n${sources.map(s=>`[${s.number}] ${s.title} — ${s.authors.length?s.authors.join(', '):s.publisher} — ${s.year||'n.d.'}\n${s.url}`).join('\n\n')}\n\n${vi?'Bản demo: AI tổng hợp từ abstract/trích đoạn, không phải toàn văn. Hãy mở nguồn để kiểm chứng.':'Demo: synthesized from indexed abstracts/excerpts, not full text. Verify original sources.'}`}
 function download(){const url=URL.createObjectURL(new Blob([text()],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='vespersignal-research.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function save(){try{const old=JSON.parse(localStorage.getItem('vesper-research-notes')||'[]');const notes=Array.isArray(old)?old:[];localStorage.setItem('vesper-research-notes',JSON.stringify([{query,content:text(),saved_at:new Date().toISOString()},...notes].slice(0,30)));setSaved(true)}catch{setError(vi?'Không đủ bộ nhớ trình duyệt. Bạn có thể tải file.':'Browser storage unavailable. Download the file instead.')}}
 if(!items.length)return null;
 return <section className="research-summary" aria-labelledby="research-heading"><header><div><span className="research-eyebrow">{vi?'VESPER NGHIÊN CỨU · BẢN THỬ NGHIỆM':'VESPER RESEARCH · DEMO'}</span><h3 id="research-heading"><Sparkles size={20}/>{vi?'Từ nhiều nguồn, đến một góc nhìn':'From sources to a clearer picture'}</h3></div><Link href="/about">{vi?'Ý tưởng dự án':'About the project'} →</Link></header>
 <p>{vi?'Khách có 5 lượt AI/ngày, không cần đăng nhập; đặt lại lúc 00:00 giờ Việt Nam. Chọn 2–8 nguồn để AI tổng hợp câu trả lời kèm trích dẫn. Mỗi lần tổng hợp mới dùng một lượt AI; xem lại bản đã lưu không gọi AI lại.':'Guests get 5 AI requests per day without signing in, resetting at 00:00 UTC+7. Select 2–8 sources for an answer with citations. Each new synthesis uses one AI request; cached answers need no new model call.'}</p>
 <details><summary>{vi?'Chọn nguồn tham khảo':'Choose references'} ({selected.length}/8)</summary><div className="research-source-picker">{items.map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} disabled={busy||(!selected.includes(s.id)&&selected.length>=8)} onChange={()=>{setSelected(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id]);setAnswer(null);setSaved(false)}}/><span>{s.title}<small>{s.source_name}</small></span></label>)}</div></details>
 <div className="research-actions"><button className="research-primary" disabled={busy||selected.length<2} onClick={summarize}>{busy?<Loader2 size={16} className="animate-spin"/>:<Sparkles size={16}/>} {busy?(vi?'Đang tổng hợp…':'Synthesizing…'):(vi?'Tổng hợp AI':'AI synthesis')}</button><button disabled={!sources.length||busy} onClick={download}><Download size={15}/>{vi?'Xuất nguồn .md':'Export .md'}</button><button disabled={!sources.length||busy} onClick={save}>{saved?<Check size={15}/>:<Bookmark size={15}/>} {saved?(vi?'Đã lưu trên máy':'Saved locally'):(vi?'Lưu ghi chú':'Save note')}</button><Link href="/research-notes">{vi?'Ghi chú đã lưu':'Saved notes'}</Link></div>
 <div aria-live="polite">{error&&<p role="alert" className="research-notice">{error} {login&&<Link href="/login">{vi?'Đăng nhập':'Sign in'} →</Link>}</p>}{answer&&answer.status!=='ready'&&<p className="research-notice">{answer.detail}</p>}
 {answer?.status==='ready'&&<div className="research-answer"><h4>{vi?'Tóm tắt AI':'AI Summary'}</h4>{answer.paragraphs?.map((p,i)=><p key={i}>{p.text} {p.sources.map(n=><a key={n} href={'#research-source-'+n} aria-label={`Source ${n}`}>[{n}] </a>)}</p>)}{answer.limitations&&<p className="research-notice"><strong>{vi?'Giới hạn bằng chứng: ':'Evidence limitations: '}</strong>{answer.limitations}</p>}</div>}</div>
 <h4>{vi?'Nguồn tham khảo':'Sources'}</h4><ol className="research-references">{sources.map(s=><li id={'research-source-'+s.number} key={s.id}><span>[{s.number}]</span><div><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} <ArrowUpRight size={13}/></a><small>{s.authors.length?s.authors.join(', '):s.publisher+' · '+(vi?'Chưa có tác giả':'Author unavailable')} · {s.year||(vi?'Chưa có năm xuất bản':'Year unavailable')}{s.coverage==='title_only'?' · '+(vi?'Chỉ có tiêu đề, không dùng để tổng hợp':'Title only; excluded from synthesis'):''}</small></div></li>)}</ol>
 <p className="research-footnote">{vi?'AI hiện đọc abstract và trích đoạn có trong chỉ mục tìm kiếm. Trích dẫn giúp đối chiếu nguồn, không bảo đảm mọi kết luận đều đúng. Bạn quyết định nguồn nào phù hợp với nghiên cứu.':'AI reads abstracts and indexed excerpts. Citations help verification but do not guarantee correctness. You decide which sources fit your research.'}</p></section>
}
