"use client";
import {useEffect,useState} from 'react';
import {discoverTopic} from '@/lib/discover-topic';
import ResearchSummary from './ResearchSummary';
import Link from 'next/link';
import {Globe,Search,ArrowUpRight,RefreshCw} from 'lucide-react';
import {useLocale} from '@/components/ui/Language';
type Result={id:string;title:string;summary:string;source_name:string;published_at:string|null;discovery_kind:string;source_url:string;ai_generated:boolean;authors?:string[]};
export default function WebDiscovery(){
 const vi=useLocale()==='vi';const [restored,setRestored]=useState(false);const [mode,setMode]=useState('all');const [sources,setSources]=useState<Record<string,string>>({});const [input,setInput]=useState('');const [query,setQuery]=useState('');const [items,setItems]=useState<Result[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [checked,setChecked]=useState('');const [tick,setTick]=useState(0);
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('vesper-news-search')||'null');if(data){setInput(typeof data.input==='string'?data.input:'');setQuery(typeof data.query==='string'?data.query:'');if(['all','news','web','research'].includes(data.mode))setMode(data.mode)}}catch{}setRestored(true)},[]);
 useEffect(()=>{if(restored)try{localStorage.setItem('vesper-news-search',JSON.stringify({input,query,mode}))}catch{}},[input,query,mode,restored]);
 useEffect(()=>{if(!restored||!query)return;setItems([]);const ctrl=new AbortController();setBusy(true);setError('');discoverTopic({query,language:vi?'vi':'en',mode},ctrl.signal).then(d=>{setItems(d.items);setSources(d.source_status||{});setChecked(d.checked_at)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!ctrl.signal.aborted)setBusy(false)});return()=>ctrl.abort()},[query,vi,tick,mode,restored]);
 useEffect(()=>{if(!query)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')setTick(n=>n+1)},900000);return()=>clearInterval(timer)},[query]);
 return <section className="nr-discovery"><div className="nr-discovery-heading"><div><span><Globe size={14}/> {vi?'KHÁM PHÁ ĐA NGUỒN':'DISCOVER ACROSS PUBLISHERS'}</span><h2>{vi?'Bạn muốn tìm hiểu điều gì?':'What would you like to explore?'}</h2></div></div><p>{vi?'Tìm mọi chủ đề: tin tức, trang web và bài nghiên cứu. Kết quả lấy trực tiếp từ các nguồn tìm kiếm, kèm liên kết gốc.':'Explore any topic across news, websites and research, with original source links.'}</p><div className="nr-discovery-suggestions" role="group" aria-label={vi?'Phạm vi tìm kiếm':'Search scope'}>{[['all',vi?'Tất cả':'All'],['news',vi?'Tin tức':'News'],['web','Web'],['research',vi?'Nghiên cứu':'Research']].map(([key,label])=><button key={key} type="button" aria-pressed={mode===key} style={mode===key?{borderColor:'currentColor',fontWeight:700}:undefined} onClick={()=>{if(key!==mode){setMode(key);setItems([])}}}>{label}</button>)}</div><form className="nr-search" onSubmit={e=>{e.preventDefault();const value=input.trim();if(value.length<2)return;setItems([]);setQuery(value);setTick(n=>n+1)}}><Search size={18}/><input minLength={2} maxLength={120} required value={input} onChange={e=>{setInput(e.target.value);if(!e.target.value.trim()){setQuery('');setItems([]);setError('');setBusy(false);setChecked('');setSources({})}}} placeholder={vi?'Ví dụ: du lịch Đà Nẵng, bóng đá, y học, machine learning…':'Try travel, football, medicine, machine learning…'} aria-label={vi?'Tìm chủ đề trên web':'Search topics on the web'}/><button disabled={busy}>{busy?<RefreshCw size={16}/>:vi?'Tìm trên web':'Search the web'}</button></form><div className="nr-discovery-suggestions">{(vi?['machine learning','AI trong giáo dục đại học','biến đổi khí hậu','bóng đá']:['machine learning','AI in higher education','climate change','football']).map(s=><button key={s} onClick={()=>{setInput(s);setQuery(s);setItems([]);setTick(n=>n+1)}}>{s}</button>)}</div>
 {query&&<div aria-live="polite"><div className="nr-discovery-caption"><strong>{query}</strong><span>{busy?(vi?'Đang tìm, hệ thống sẽ tự thử lại nếu kết nối gián đoạn…':'Searching; temporary connection failures are retried automatically…'):error?(vi?'Tìm kiếm chưa hoàn tất':'Search incomplete'):`${items.length} ${vi?'kết quả':'results'}`}</span>{checked&&!busy&&<small>{vi?'Đã kiểm tra ':'Checked '}{new Date(checked).toLocaleTimeString(vi?'vi-VN':'en-GB')}</small>}</div>{error?<p role="alert">{error} <button onClick={()=>setTick(n=>n+1)}>{vi?'Thử lại':'Retry'}</button></p>:!busy&&!items.length?<p>{vi?'Chưa có kết quả. Thử từ khóa khác hoặc đổi VI/EN.':'No results. Try another query or switch VI/EN.'}</p>:<div className="nr-discovery-results">{items.map(a=><article key={a.id}><small>{a.discovery_kind==='research'?(vi?'Nghiên cứu · ':'Research · '):''}{a.source_name}{a.authors?.length?' · '+a.authors.join(', '):''}{a.published_at?' · '+new Date(a.published_at).toLocaleDateString(vi?'vi-VN':'en-GB'):''}</small><Link href={'/news/'+a.id}><h3>{a.title}</h3></Link>{a.summary&&<p>{a.summary.slice(0,240)}{a.summary.length>240?"…":""}</p>}<a href={a.source_url} target="_blank" rel="noopener noreferrer">{vi?'Mở nguồn':'Open source'}<ArrowUpRight size={13}/></a></article>)}</div>}</div>}
 {query&&<ResearchSummary query={query} items={items}/>}<small className="nr-discovery-note">{Object.entries(sources).filter(([,status])=>status!=="ok").map(([name])=><span key={name}>{name}: {vi?"tạm không phản hồi. ":"temporarily unavailable. "}</span>)}{vi?'Nguồn: Google News, Bing Web RSS và Crossref (nghiên cứu). Không bảo đảm bao phủ toàn bộ Internet; kết quả giữ thứ tự liên quan từ từng nguồn. Bản xem trước có thể chỉ có tiêu đề; tóm tắt AI chỉ dùng thông tin nguồn cung cấp. Chủ đề đang mở tự kiểm tra mỗi 15 phút.':'Sources: Google News, Bing Web RSS and Crossref research. Coverage is not exhaustive; results preserve each provider’s relevance order. Previews may contain only headlines; AI summaries use only supplied information. The open topic refreshes every 15 minutes.'}</small></section>
}


